parameters:
  - name: packageName
    type: string
  - name: tarballName
    type: string

stages:
  - stage: Publish artifact
    displayName: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
            clean: true
            fetchDepth: 1

          - task: NodeTool@0
            displayName: Use Node.js 18.x
            inputs:
              versionSpec: 18.x

          - task: CmdLine@2
            displayName: Install pnpm
            inputs:
              script: npm install -g pnpm

          - task: CmdLine@2
            displayName: Audit
            inputs:
              script: pnpm audit --audit-level=high

          - task: CmdLine@2
            displayName: Install dependencies
            inputs:
              script: pnpm install --filter ${{ parameters.packageName }}

          - task: CmdLine@2
            displayName: Build package
            inputs:
              script: npm run build
              workingDirectory: packages/${{ parameters.packageName }}/

          - task: CmdLine@2
            displayName: Run unit tests
            inputs:
              script: npm run test:cover
              workingDirectory: packages/${{ parameters.packageName }}/

      - job: Publish
        dependsOn: Build
        steps:
          - task: CmdLine@2
            displayName: Pack package files
            inputs:
             script: pnpm pack
             workingDirectory: packages/${{ parameters.packageName }}/

          - publish: packages/${{ parameters.packageName }}/${{ parameters.tarballName }}
            displayName: Publish package artifact
            artifact: published-package
