contact_links:
  - name: Questions 🤔
    url: https://github.com/iTwin/saved-views-react/discussions/categories/q-a
    about: Ask questions and get help from contributors through GitHub Discussions.
