trigger:
  tags:
    include:
      - v*.*.*

pr: none

variables:
  - name: packageName
    value: saved-views-react
  - name: packageVersion
    value: ${{ replace(variables['Build.SourceBranchName'], 'v', '') }}
  - name: tarballName
    value: itwin-$(packageName)-$(packageVersion).tgz

resources:
  repositories:
    - repository: templates
      type: git
      name: iModelTechnologies/imodeljs-build-pipeline-scripts

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
            clean: true
            fetchDepth: 1

          - task: NodeTool@0
            displayName: Use Node.js 18.x
            inputs:
              versionSpec: 18.x

          - task: CmdLine@2
            displayName: Install pnpm
            inputs:
              script: npm install -g pnpm

          - task: CmdLine@2
            displayName: Audit
            inputs:
              script: pnpm audit --audit-level=high

          - task: CmdLine@2
            displayName: Install dependencies
            inputs:
              script: pnpm install --filter $(packageName)

          - task: CmdLine@2
            displayName: Build package
            inputs:
              script: npm run build
              workingDirectory: packages/$(packageName)/

          - task: CmdLine@2
            displayName: Run unit tests
            inputs:
              script: npm run test:cover
              workingDirectory: packages/$(packageName)/

          - task: CmdLine@2
            displayName: Pack package files
            inputs:
             script: pnpm pack
             workingDirectory: packages/$(packageName)/

          - publish: packages/$(packageName)/$(tarballName)
            displayName: Publish package artifact
            artifact: published-package

  - stage: publish
    dependsOn: build
    displayName: Publish
    jobs:
      - template: templates/npmjs-publish-deployment.yaml@templates
        parameters:
          path: $(tarballName)
          artifactName: published-package
