trigger:
  tags:
    include:
      - v*.*.*-react

pr: none

variables:
  - name: packageName
    value: saved-views-react
  - name: packageVersion
    # Build.SourceBranchName will be a tag that triggereed the pipeline, like "v1.2.3-react"
    value: ${{ replace(replace(variables['Build.SourceBranchName'], '-react', ''), 'v', '') }}
  - name: tarballName
    value: itwin-$(packageName)-$(packageVersion).tgz

resources:
  repositories:
    - repository: templates
      type: git
      name: iModelTechnologies/imodeljs-build-pipeline-scripts

stages:
  - template: /publish-artifact.yaml
    parameters:
      packageName: $(packageName)
      tarballName: $(tarballName)

  - stage: publish
    dependsOn: build
    displayName: Publish
    jobs:
      - template: templates/npmjs-publish-deployment.yaml@templates
        parameters:
          path: $(tarballName)
          artifactName: published-package
