name: CI

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9
        run_install: false

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install

    - name: ESLint
      run: npm run lint -- --max-warnings 0

    - name: Typecheck
      run: npm run typecheck

    - name: Check saved-views-client unit test coverage
      run: npm run test:cover --prefix ./packages/saved-views-client

    - name: Check saved-views-react unit test coverage
      run: npm run test:cover --prefix ./packages/saved-views-react

    - name: Check if changeset is present
      if: github.actor != 'imodeljs-admin'
      run: |
        # There are issues with changesets in github workflows, so we need to force pull the master branch
        # Fix for issue https://github.com/changesets/changesets/issues/517#issuecomment-884778604
        git pull -f origin master:master
        pnpm changeset status --since=master
